### PR TITLE
Script to download files from Amazon s3 bucket

### PR DESCRIPTION
**Pull request by RaulOlivaO**
Please review the file.

You can change the value of s3_folder_key, currently is "goldenPath/hs1/bigZips/genes".
You can change the value of local_folder variable too.

### CODE REVIEW

**Comment by ThakkarRajan** [comment]
This is our dataset link 
https://www.cbioportal.org/study/summary?id=msk_ch_2020
Can you try to open this?

**Review by ThakkarRajan — COMMENTED** [review]
LGTM

**Review by ThakkarRajan — CHANGES_REQUESTED** [review]
This is our dataset link
https://www.cbioportal.org/study/summary?id=msk_ch_2020
Can you try to open this?

**Comment by RaulOlivaO** [comment]
> This is our dataset link https://www.cbioportal.org/study/summary?id=msk_ch_2020 Can you try to open this?

This dataset was indicated by Research team?

**Comment by melvinmildrick** [comment]
> This is our dataset link https://www.cbioportal.org/study/summary?id=msk_ch_2020 Can you try to open this?

Yes I can open this. Do we have to do anything with this dataset?

**Comment by melvinmildrick** [comment]
> This is our dataset link https://www.cbioportal.org/study/summary?id=msk_ch_2020 Can you try to open this?

Yes I can open this. Do we have to do anything with this dataset?

**Comment by sujaymacwan** [comment]
> > This is our dataset link https://www.cbioportal.org/study/summary?id=msk_ch_2020 Can you try to open this?
> 
> This dataset was indicated by Research team?

This is the approved data set link

**Review by melvinmildrick — APPROVED** [review]
It looks good to me

**Pull request closed without merging**
