### PR TITLE
Wrote the function to get the file from s3

### PR DESCRIPTION
**Pull request by Kranthi-566**

### CODE REVIEW

**Review by ThakkarRajan — COMMENTED** [review]
This file is not required right now, As we find the dataset from a different source. However, I will let you know if we need it.

**Comment by ThakkarRajan** [comment]
Thank you

**Comment by Kranthi-566** [comment]
This issue is created by professor and as this is the code related to the issue and this code is just a placeholder. @ThakkarRajan

**Review by ThakkarRajan — CHANGES_REQUESTED** [review]
This is our dataset link
https://www.cbioportal.org/study/summary?id=msk_ch_2020
Can you try to open this?

**Comment by Kranthi-566** [comment]
I'm able to open the link, not sure how this is related to the function I've written.

**Review by melvinmildrick — APPROVED** [review]
LGTM

**Comment by ThakkarRajan** [comment]
Okay just add this file to Data Collection folder. I will approve it

**Review by ThakkarRajan — APPROVED** [review]
LGTM

**Pull request merged**
